In [141]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore")

In [142]:
data=pd.read_csv("C:/Users/DELL/nlp/Sentimentdataset/sentimentdataset.csv")

In [143]:
data.shape

(732, 15)

In [144]:
data

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,728,732,Collaborating on a science project that receiv...,Happy,2017-08-18 18:20:00,ScienceProjectSuccessHighSchool,Facebook,#ScienceFairWinner #HighSchoolScience,20.0,39.0,UK,2017,8,18,18
728,729,733,Attending a surprise birthday party organized ...,Happy,2018-06-22 14:15:00,BirthdayPartyJoyHighSchool,Instagram,#SurpriseCelebration #HighSchoolFriendship,25.0,48.0,USA,2018,6,22,14
729,730,734,Successfully fundraising for a school charity ...,Happy,2019-04-05 17:30:00,CharityFundraisingTriumphHighSchool,Twitter,#CommunityGiving #HighSchoolPhilanthropy,22.0,42.0,Canada,2019,4,5,17
730,731,735,"Participating in a multicultural festival, cel...",Happy,2020-02-29 20:45:00,MulticulturalFestivalJoyHighSchool,Facebook,#CulturalCelebration #HighSchoolUnity,21.0,43.0,UK,2020,2,29,20
731,732,736,Organizing a virtual talent show during challe...,Happy,2020-11-15 15:15:00,VirtualTalentShowSuccessHighSchool,Instagram,#VirtualEntertainment #HighSchoolPositivity,24.0,47.0,USA,2020,11,15,15

In [145]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  732 non-null    int64
 1   Unnamed: 0    732 non-null    int64
 2   Text          732 non-null    object
 3   Sentiment     732 non-null    object
 4   Timestamp     732 non-null    object
 5   User          732 non-null    object
 6   Platform      732 non-null    object
 7   Hashtags      732 non-null    object
 8   Retweets      732 non-null    float64
 9   Likes         732 non-null    float64
 10  Country       732 non-null    object
 11  Year          732 non-null    int64
 12  Month         732 non-null    int64
 13  Day           732 non-null    int64
 14  Hour          732 non-null    int64
dtypes: float64(2), int64(6), object(7)
memory usage: 85.9+ KB

In [146]:
data.describe()

,Unnamed: 0.1,Unnamed: 0,Retweets,Likes,Year,Month,Day,Hour
count,732.000000,732.000000,732.000000,732.000000,732.000000,732.000000,732.000000,732.000000
mean,366.464481,369.740437,21.508197,42.901639,2020.471311,6.122951,15.497268,15.521858
std,211.513936,212.428936,7.061286,14.089848,2.802285,3.411763,8.474553,4.113414
min,0.000000,0.000000,5.000000,10.000000,2010.000000,1.000000,1.000000,0.000000
25%,183.750000,185.750000,17.750000,34.750000,2019.000000,3.000000,9.000000,13.000000
50%,366.500000,370.500000,22.000000,43.000000,2021.000000,6.000000,15.000000,16.000000
75%,549.250000,553.250000,25.000000,50.000000,2023.000000,9.000000,22.000000,19.000000
max,732.000000,736.000000,40.000000,80.000000,2023.000000,12.000000,31.000000,23.000000

In [147]:
data.isnull().sum()

Unnamed: 0.1    0
Unnamed: 0      0
Text            0
Sentiment       0
Timestamp       0
User            0
Platform        0
Hashtags        0
Retweets        0
Likes           0
Country         0
Year            0
Month           0
Day             0
Hour            0
dtype: int64

In [148]:
data.duplicated().sum()

0

In [149]:
data = data.drop(['Unnamed: 0','Unnamed: 0.1','Timestamp'], axis = 1)

In [150]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Text       732 non-null    object
 1   Sentiment  732 non-null    object
 2   User       732 non-null    object
 3   Platform   732 non-null    object
 4   Hashtags   732 non-null    object
 5   Retweets   732 non-null    float64
 6   Likes      732 non-null    float64
 7   Country    732 non-null    object
 8   Year       732 non-null    int64
 9   Month      732 non-null    int64
 10  Day        732 non-null    int64
 11  Hour       732 non-null    int64
dtypes: float64(2), int64(4), object(6)
memory usage: 68.8+ KB

In [151]:
data.nunique()

Text         707
Sentiment    279
User         685
Platform       4
Hashtags     697
Retweets      26
Likes         38
Country      115
Year          14
Month         12
Day           31
Hour          22
dtype: int64

In [152]:
import re
import nltk
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS as stop_words
from nltk.stem import WordNetLemmatizer

In [153]:
lemmatizer = WordNetLemmatizer()

In [154]:
def clean_text(text):
    # Remove special characters and replace them with spaces
    text = re.sub(r'\W', ' ', text)

    # Convert all characters to lowercase
    text = text.lower()

    # Tokenize the text (split it into individual words)
    words = text.split()

    # Remove stop words and lemmatize each word
    cleaned_words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]

    # Join the cleaned words back into a single string
    return ' '.join(cleaned_words)

In [155]:
data['cleaned_text'] = data['Text'].apply(clean_text)

In [156]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize a TF-IDF vectorizer with a maximum of 500 features (terms)
tfidf_vectorizer = TfidfVectorizer(max_features=500)

# Apply the TF-IDF vectorizer to the cleaned email text data and transform it into numerical features
inputs = tfidf_vectorizer.fit_transform(data['cleaned_text'])

In [157]:
X = data.drop('Sentiment', axis=1)
y= data.Sentiment.to_frame()

In [158]:
X_train , X_test , y_train , y_test = train_test_split(X,y,train_size=0.70,random_state=3)
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(512, 12) (512, 1)
(220, 12) (220, 1)

In [159]:
# Select all object (categorical) columns
X_train_cat = X_train.select_dtypes(include=['object'])

# Exclude a particular column (e.g., 'column_name')
X_train_cat = X_train_cat.drop(columns=['cleaned_text','Text'])

# Check the result
X_train_cat

,User,Platform,Hashtags,Country
718,BirthdaySurpriseHighSchool,Instagram,#SurpriseParty #HighSchoolCelebration,UK
598,NostalgiaExplorer,Twitter,#ChildhoodMemories #TeenCartoons,USA
326,RuinedHeart,Instagram,#Devastated #EchoesOfShatteredDreams,Australia
574,GardeningEnthusiastFlowerGarden,Instagram,#NaturesBeauty #FloralJoy,Australia
224,VisionarySpirit,Instagram,#Determination #UnparalleledHeights,UK
...,...,...,...,...
659,TikTokFailHighSchool,Facebook,#DanceFail #HighSchoolTikTok,USA
256,PhoenixExplorer,Twitter,#Inspired #CreativePhoenix,UK
643,CodeExplorerHighSchool,Twitter,#CodingAdventure #HighSchoolCoderLife,UK
249,DreamPainter,Instagram,#Hopeful #CanvasOfDreams,India
664,SnackNinjaHighSchool,Twitter,#SnackNinja #HighSchoolSnacks,USA

In [160]:
X_train_num = X_train.select_dtypes(include=['int64','float64'])

In [161]:
# Select all object (categorical) columns
X_test_cat = X_test.select_dtypes(include=['object'])

# Exclude a particular column (e.g., 'column_name')
X_test_cat = X_test_cat.drop(columns=['cleaned_text','Text'])

# Check the result
X_test_cat

,User,Platform,Hashtags,Country
80,NewParentJoy,Instagram,#Happiness #NewFamilyMember,UK
97,KindnessObserver,Twitter,#Kindness #ActsOfKindness,USA
559,SoccerPlayerOwnGoalMoment,Twitter,#Despair #OwnGoal,Spain
406,FamilyGatherer,Facebook,#Gratitude #FamilyLaughter,Austria
124,SimpleJoys,Twitter,#Contentment #SundayMood,Australia
...,...,...,...,...
30,RoadTripper,Instagram,#RoadTrip #ScenicViews,UK
322,NightPrisoner,Twitter,#Fearful #LurkingMonsters,India
114,OptimisticSoul,Facebook,#Hope #Optimism,USA
458,TapestrySorrow,Facebook,#Despair #UnraveledHope,India
453,RiverOfSorrow,Instagram,#Sorrow #AutumnLeaves,Canada

In [162]:
X_test_num = X_test.select_dtypes(include=['int64','float64'])

In [163]:
scaler = StandardScaler()
X_train_num_rescaled = pd.DataFrame(scaler.fit_transform(X_train_num),
                                   columns=X_train_num.columns,
                                   index=X_train_num.index)
X_test_num_rescaled = pd.DataFrame(scaler.transform(X_test_num),
                                   columns=X_test_num.columns,
                                   index=X_test_num.index)
X_train_num_rescaled.head()
X_test_num_rescaled.head()

     Retweets     Likes      Year     Month       Day      Hour
80   1.223194  1.235839  0.909588 -1.224642  0.771996 -1.366951
97  -0.203076 -0.193619  0.909588 -1.224642  1.487402 -1.120948
559  0.082178  0.163745 -0.982000  1.731589 -0.062645  1.093080
406  0.082178  0.163745 -1.360318  1.731589  1.487402  0.847077
124  1.223194  1.235839 -4.008542  0.549097 -0.062645 -1.366951

In [194]:
from sklearn.preprocessing import LabelEncoder

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Apply label encoding to each column in X_train_encoded and X_test_encoded
# Make sure the columns in X_train_encoded and X_test_encoded are categorical

# For X_train_encoded
X_train_encoded= X_train_encoded.apply(label_encoder.fit_transform)

# For X_test_encoded (ensure to use the same encoder for consistency)
X_test_encoded= X_test_encoded.apply(label_encoder.transform)

In [196]:
X_train_encoded

,User_ AdeleConcertGoer,User_ AdeleMelodyTearjerker,User_ AdventureAwaits,User_ AdventureSeeker,User_ AdventureX,User_ AffectionSender,User_ AloofObserver,User_ AlpsSkiAdventurer,User_ AmazonExplorer,User_ AmusedSoul,...,Country_ USA,Country_ USA,Country_ USA,Country_ USA,Country_ USA,Country_ USA,Country_ USA,Country_ USA,Country_ USA,Country_USA
718,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
598,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
326,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
574,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
224,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
659,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
256,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
643,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
664,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [198]:
X_test_encoded

,User_ AdventureAwaits,User_ AngkorWatAdventurer,User_ ApatheticObserver,User_ ArchaeologyEnthusiast,User_ ArtAppreciator,User_ ArtConnoisseur,User_ ArtisticSenior,User_ BakeSaleRecipeExperimentHighSchool,User_ BirthdayBash,User_ BirthdayPartyPlannerHighSchool,...,Country_ USA,Country_ USA,Country_ USA,Country_ USA,Country_ USA,Country_ USA,Country_ USA,Country_ USA,Country_ USA,Country_USA
80,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
559,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
406,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
124,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
322,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
114,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
458,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
453,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [200]:
X_test_encoded = X_test_encoded.reindex(columns=X_train_encoded.columns, fill_value=0)

In [202]:
X_test_encoded.shape

(220, 1079)

In [204]:
X_train_encoded.shape

(512, 1079)

In [ ]:
X_train_transformed = pd.concat([X_train_num_rescaled, X_train_encoded,data['cleaned_text']], axis=1)
X_test_transformed = pd.concat([X_test_num_rescaled, X_test_encoded], axis=1)